#!/usr/bin/env bash
# Installing Nginx on the web server

sudo apt-get update -y

sudo apt-get install nginx -y

sudo chown -R "$USER":"$USER" /var/www/html

echo 'Hello World!' > /var/www/html/index.nginx-debian.html

sudo sed -i '24i\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
