#!/usr/bin/env bash
# script that install and configure Haproxy to load balancer
# haproxy installation
sudo apt-get -y update
sudo apt-get -y install haproxy
# edit haproxy config file
add_config=\
"
frontend http
        bind *:80
        mode http
        default_backend my_servers
backend my_servers
        balance roundrobin
        server 484113-web-01 18.210.15.71:80 check
        server 484113-web-02 54.157.136.110:80 check
"
echo "$add_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
