#!/usr/bin/env bash
# Debugging the listen port 80 Nginx
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo nginx -t
sudo service nginx restart
kill "$(pgrep 'nginx' | head -1)"
