#!/usr/bin/env bash
# Nginx debugging script

sudo chmod 644 /etc/nginx/nginx.conf

sudo sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf

sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-enabled/default
sudo sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen [::]:8080 default_server;/g' /etc/nginx/sites-enabled/default

pkill apache2

sudo -u nginx service nginx restart
